### PR TITLE
Feature/es6

### PR DESCRIPTION
**Pull request by HelloEdit**
I do not have the time to take care of transforming the code, my projects are waiting for me!

But do not worry, the hardest is already done, it remains only to correct the bugs with Karma

### CODE REVIEW

**Comment by rojobuffalo** [comment]
@HelloEdit sorry, I don't know off the top of my head why that is happening. Do you have any ideas about it?

**Comment by HelloEdit** [comment]
@rojobuffalo his is the whole question, the code is written and in my opinion almost correct, but karma does not seem to pass the test ...
(PS: could you create a branch feature / es6 on your repository to be able to ask for help? If so, I would create a PR in this new branch)

**Comment by HelloEdit** [comment]
`this.muiComponent` it seems to be the source of the problem

**Comment by rojobuffalo** [comment]
@HelloEdit ok, I just created branch `dev/es6`.

**Comment by HelloEdit** [comment]
Continue on #233

**Pull request closed without merging**
